server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 9000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:

  sql:
    init:
      data-locations:
        - classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: create # none, update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true